- project:
    templates:
      - build-openstack-docs-pti
      - check-requirements
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs
    check:
      jobs:
        - vmware-tox-lower-constraints
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py27:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py35:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py36:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
    gate:
      queue: vmware-nsx
      jobs:
        - vmware-tox-lower-constraints
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py27:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py35:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py36:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia

- job:
    name: vmware-tox-lower-constraints
    parent: openstack-tox-lower-constraints
    timeout: 5400
    required-projects:
      - openstack/neutron
      - openstack/networking-l2gw
      - openstack/networking-sfc
      - openstack/neutron-lbaas
      - openstack/vmware-nsxlib
      - openstack/neutron-fwaas
      - openstack/neutron-dynamic-routing
      - openstack/neutron-vpnaas
      - openstack/tap-as-a-service
      - openstack/octavia
