#!/bin/bash

# Copyright 2015 VMware, Inc.
#
# All Rights Reserved
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

NSX_XTRACE=$(set +o | grep xtrace)
set +o xtrace

if [[ $Q_PLUGIN == 'vmware_nsx' ]]; then
    NSX_GATEWAY_NETWORK_INTERFACE=${NSX_GATEWAY_NETWORK_INTERFACE:-eth2}
    # Re-declare floating range as it's needed also in stop_vmware_nsx, which
    # is invoked by unstack.sh
    FLOATING_RANGE=${FLOATING_RANGE:-172.24.4.0/24}
fi

$NSX_XTRACE
